### ISSUE TITLE
Create the VueJS base of the memory card game 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#17]
Please add the base for the the VueJS 

Skeleton for VueJS @lates version
the app will have the cards and the grid layout with the base CSS 
Leaven the front face and back-face image no implemented 
No logic required

**Comment by alkhimch** [comment]
@GeraAlcantara  can you assign to me this task. I'm VueJS developer

**Comment by alkhimch** [comment]
@GeraAlcantara  please check pull request. [https://github.com/GeraAlcantara/cards-memory-game/pull/21](url)

**Comment by GeraAlcantara** [comment]
#21 this PR close the issue
