### ISSUE TITLE
React Game (and maybe others) stops working on refresh 

### ISSUE THREAD

**Issue by arthurmatthew** [GeraAlcantara/cards-memory-game#19]
The game itself worked fine until I refreshed the page to restart the game, it did not work. The cards flipped around which made it look like the game was reset, however I was unable to interact with the cards (flip them). 

This happened while I was working on the React version of the game in Visual Studio Code. The only way I was able to fix the game was by re-rendering the entire thing.

**Comment by GeraAlcantara** [comment]
Adding a new issue #20 please refer to this one in the future
