### ISSUE TITLE
React Version BUG 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#20]
It look the game is no working properly on the React version 

Please see the implementation under the React Folder

**Comment by GeraAlcantara** [comment]
Base comment #19 of this issue

**Comment by saket2508** [comment]
Hi @GeraAlcantara, Can you assign this bug to me? Was actually debugging the current implementation.

**Comment by GeraAlcantara** [comment]
hi @saket2508 
Happy coding

**Comment by GeraAlcantara** [comment]
close with PR #25
