### ISSUE TITLE
Create Memory Card Game using React 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#3]
# Hi! Hacktoberfest Fans and followers 

I'll like to have the same memory game using React library 

Add the code inside the React Folder 

Remember to fork first then make a new branch linking the issue and made the PR

Please check the [contribution.md](https://github.com/GeraAlcantara/cards-memory-game/blob/main/CONTRIBUTING.md)

**Comment by arthurmatthew** [comment]
I can work on this.

**Comment by GeraAlcantara** [comment]
Sure

**Comment by Yh010** [comment]
can I also work on this issue?

**Comment by Yh010** [comment]
do you want us to improve your existing react folder or can we add some new code from our side?

**Comment by GeraAlcantara** [comment]
> do you want us to improve your existing react folder or can we add some new code from our side?

Hi @Yh010 
Improve the existing code will be great so you can have a feeling how is to collaborate with others

**Comment by arthurmatthew** [comment]
I agree. It would also help me because I am a beginner react developer and if you see a mistake that you want to fix or anything like that, I will be able to learn.

**Comment by saket2508** [comment]
Hey. I too would love to have a look at the React code and see if it can be improved/optimized. Can I contribute straightaway by referring to the contributing docs or do I need be assigned to this issue?

**Comment by arthurmatthew** [comment]
By the way, I am a beginner react developer. I made the first version of the React memory card game in this repo. If you guys have any feedback or things that you notice while looking at the code, that would be awesome

**Comment by GeraAlcantara** [comment]
hi @saket2508 

I think to mange this better probably it will be a good practice to create an issue of a missing implementation in the React app as it is at the moment, compare the example and add to the issues wich part you will like to implement.

**Comment by GeraAlcantara** [comment]
@arthurmatthew can you be so kind to create an issue with some of the features still missing the first react version

**Comment by saket2508** [comment]
@GeraAlcantara Hey. Yeah that's cool. Let me see if the code can be improved upon. Will create an issue if I find something.

**Comment by satrio-pamungkas** [comment]
@GeraAlcantara Can I contribute with typescript version ? I will put it on different folder

**Comment by Kusha-web** [comment]
@GeraAlcantara Should I add a reshuffle button to initiate the game or shuffling the cards etc..

**Comment by GeraAlcantara** [comment]
Hi @satrio-pamungkas 
I have add a new folder structure to add the typeScript flavor to Vanilla, VueJs and React

**Comment by kyojurocode** [comment]
Hey. Can I work on the React code for this issue .
