### ISSUE TITLE
VueJS Version Implement a loop to create each component -->

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#31]
https://github.com/GeraAlcantara/cards-memory-game/blob/51f311979b87097113910889ce01d858e0aa30a3/VUE/src/views/GameView.vue#L4

**Comment by amit-ksh** [comment]
Can I work on this?

**Comment by GeraAlcantara** [comment]
Sure @amit-ksh 
Happy coding !
