### ISSUE TITLE
Remove console log Typescript-React Version 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#33]
https://github.com/GeraAlcantara/cards-memory-game/blob/05c42919f964b3b4de9af55403aebeb8cab0ce73/TypeScript/TypeScript-React/src/App.tsx#L27

**Comment by FreemRL** [comment]
Hey I created a PR (#34) for this issue :)

**Comment by GeraAlcantara** [comment]
close with #34
