### ISSUE TITLE
[bug]: card remains flipped when card was double clicked both in React and Vue app

### ISSUE THREAD

**Issue by amit-ksh** [GeraAlcantara/cards-memory-game#38]
https://user-images.githubusercontent.com/91947037/193495824-361b3c40-b946-4e3e-a267-ded4a9236460.mp4

https://user-images.githubusercontent.com/91947037/193495832-70f8f6a1-146e-4f25-9f8d-62e43fc4bedf.mp4

**Comment by GeraAlcantara** [comment]
Anyone willing to take this issue ? 
We can split it on two 
React
Vue
