### ISSUE TITLE
Create Memory Card Game using React

### ISSUE THREAD

**Issue by 0xriyadh** [GeraAlcantara/cards-memory-game#39]
I would like to make the game in React

**Comment by GeraAlcantara** [comment]
Is all ready implemente in the folder React

**Comment by GeraAlcantara** [comment]
try to see if is anything in the code that can by refactor

**Comment by GeraAlcantara** [comment]
I could open a new issue to aply the new hover state and pointer as the base game

**Comment by GeraAlcantara** [comment]
Maybe you can work on the #38 on react

**Comment by GeraAlcantara** [comment]
please ask the assignment there
