### ISSUE TITLE
[bug]: card remains flipped when card was double clicked REACT

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#40]
This is the issue for the react version 
Refers to #38

**Comment by PiXeL99-eng** [comment]
> This is the issue for the react version Refers to #38

I would like to work on this bug, please assign it to me.

**Comment by saimaheshtaduri** [comment]
Can I contribute. Assign to me. @GeraAlcantara

**Comment by komalsoni4** [comment]
please assign it to me
