### ISSUE TITLE
[bug]: card remains flipped when card was double clicked VUE

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#41]
For The VUE Version 
This is refer for the issue #38

**Comment by amit-ksh** [comment]
I would like to work on this. Can you this issue to me please?

**Comment by saimaheshtaduri** [comment]
Can I contribute. Assign to me. @GeraAlcantara

**Comment by tara-matthew** [comment]
I'm happy to take a look at this issue!

**Comment by amit-ksh** [comment]
I believe there is already PR made for this issue.
[PR link](https://github.com/GeraAlcantara/cards-memory-game/pull/42)

**Comment by tara-matthew** [comment]
Thank you for the heads up.

**Comment by GeraAlcantara** [comment]
close with PR #42
