### ISSUE TITLE
Create Memory Card Game using VueJS

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#5]
Hi! Hacktoberfest Fans and followers
I'll like to have the same memory game using VUE library

Add the code inside the VUEFolder

Remember to fork first then make a new branch linking the issue and made the PR

Please check the [contribution.md](https://github.com/GeraAlcantara/cards-memory-game/blob/main/CONTRIBUTING.md)

**Comment by RahulSankhla312** [comment]
hey @GeraAlcantara  can you assign this issue to me.

**Comment by GeraAlcantara** [comment]
Hi @RahulSankhla312 

Sure thing just I will made an other issue so you can create the base only leaving room for other to participate.

**Comment by GeraAlcantara** [comment]
@RahulSankhla312  please look into this issue #17 

replay there so I can make the assignment

**Comment by alkhimch** [comment]
can you assign to me this task. I am vue developer :) @GeraAlcantara

**Comment by GeraAlcantara** [comment]
@alkhimch 
please request the assignment on the issue  #17
