### ISSUE TITLE
Meta Description on gameBase index

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#51]
# Hello Hacktoberfest fans and followers 
Can someone create de description for the meta tag  on the index.html

**Comment by guha-rahul** [comment]
Hey i am new to open source and i want to contribute to this project, but i am failing to understand what kind of description is needed for the meta tag?

**Comment by GeraAlcantara** [comment]
@guha-rahul 

The description will be a text that describe the page. 
Hint: 
https://www.w3schools.com/tags/tag_meta.asp

text: 
Open Source project of the classic memory card game created in different flavor of JavaScript libraries

**Comment by guha-rahul** [comment]
@GeraAlcantara Thank you very much for the lead .

**Comment by guha-rahul** [comment]
hey @GeraAlcantara There are 5 different index.html files. should i need to update all the files?

**Comment by GeraAlcantara** [comment]
only inside the /gameBase folder
