### ISSUE TITLE
Game Base Fix hover effect on mobile devices

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#52]
https://user-images.githubusercontent.com/32178037/193639824-055209e7-dd3c-4551-b505-6f00b5e8c3e2.mp4

**Comment by GeraAlcantara** [comment]
Hint: 
media query for hover before the rule. 
You can google how to detect if a device handle a hover state

**Comment by AaryanSingh0017** [comment]
can you assign me?

**Comment by GeraAlcantara** [comment]
@AaryanSingh0017 
Happy coding !

**Comment by AaryanSingh0017** [comment]
In which file should I put the changes.

**Comment by GeraAlcantara** [comment]
folder gameBase/src/styles.css

**Comment by GeraAlcantara** [comment]
@AaryanSingh0017 remember to fork this repo first then create a new branch and make the changes there, when you finish place a Pull request

**Comment by FOWMind** [comment]
Let me solve it

**Comment by GeraAlcantara** [comment]
@FOWMind 
Happy coding
