### ISSUE TITLE
adapt Responsive layout to class memory-game on baseGame css 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#53]
Making reference for the original issue #50 

The class has a hard code value of 640 x 640
convert that value to a max With and Hight and adapt for smaller screens

**Comment by darshikaguptaa** [comment]
Hey can you please assign this issue to me.
I'm interested in working on this

**Comment by skyspace88** [comment]
:) !!!

**Comment by GeraAlcantara** [comment]
Assignment to @dreymotoh  since is the one who catch the issue

**Comment by GeraAlcantara** [comment]
@darshikaguptaa  let @dreymotoh come with the solution and will be need help to reflex this change on the others version even if is react, VueJS or svelte they all using a CSS file for the styles.

**Comment by skyspace88** [comment]
great :) going to work on it soon!

**Comment by GeraAlcantara** [comment]
close by #59
