### ISSUE TITLE
Ideas for include LOW OR NON CODE CONTRIBUTIONS

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#54]
### Can someone help me how we can manage the non-codes Contributions.

WRITING | TECHNICAL DOCUMENTATION | TRANSLATINGCOPY EDITING
-- | -- | --
DESIGN | TESTING | USER EXPERIENCE TESTINGGRAPHIC DESIGNVIDEO PRODUCTION
ADVOCACY** | TALKS OR PRESENTATIONSTECHNICAL BLOG POSTSPODCASTSCASE STUDIES | SOCIAL MEDIABLOG POSTS

**Guidelines** 

CONTRIBUTORS SUBMITTING LOW- OR NON-CODE CONTENT TO PROJECTS SHOULD CREATE A PR/MR TO TRACK IT. WHILE HACKTOBERFEST TRACKS ALL PR/MRS SUBMITTED FOR THE EVENT, MAINTAINERS MAY NEED TO FACILITATE TRACKING OF THOSE CONTRIBUTIONS THROUGH AN ACTIVITY LOG OR SIMILAR.

**Comment by Boamorte8** [comment]
An idea can be create a markdown file an each people add his name and the link to the post

**Comment by GeraAlcantara** [comment]
Go for it 
@Boamorte8 
Happy coding

**Comment by GeraAlcantara** [comment]
close with pr #60
