### ISSUE TITLE
Social Media Post twitter

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#58]
We are looking for a LOW- OR NON-CODE contribution that have a basic knowledge of GitHub on how to fork, create new branch, to help us have more present on Twitter. 

Task: 
redact a post linking this repo for inviting to LOW- OR NON-CODE contribution. 
https://github.com/GeraAlcantara/cards-memory-game/

**Comment by rohitranjan-2702** [comment]
I can do this, please assign me this.

**Comment by GeraAlcantara** [comment]
go for it @itzROHIT-coder

**Comment by GeraAlcantara** [comment]
Please @itzROHIT-coder 
review the examples to track the non-code contribution at [Examples](https://github.com/GeraAlcantara/cards-memory-game/blob/main/NON_CODE_CONTRIBUTIONS/EXAMPLES.md)

You still need to fork the repo and make new branch and place the pull request
