### ISSUE TITLE
Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#6]
Help wanted to improve the CONTRIBUTING.md

**Comment by eventually-delete** [comment]
Hey! How can I be of help?

**Comment by GeraAlcantara** [comment]
Can you help improve and simplify the  CONTRIBUTING.md 

The flow will be 
- Fork first 
- add a new Brach 
- make changes
- Make a Pull request

* if is from a issue link the issue on the branch name or the Pull Request

have small images to help the beginners is a most

**Comment by GeraAlcantara** [comment]
Can you work on this @yunsuklee ?

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey, I am interested. I can add images and expand a bit more on the steps. Can you assign it to me? Thank you !

**Comment by GeraAlcantara** [comment]
Sure @ABHIGYAN-MOHANTA

**Comment by ABHIGYAN-MOHANTA** [comment]
Hey man, made the pr check it out. Hope you like it.

**Comment by GeraAlcantara** [comment]
I'll look into in a couple of minutes
@ABHIGYAN-MOHANTA

**Comment by ABHIGYAN-MOHANTA** [comment]
Sure, thanks.

**Comment by GeraAlcantara** [comment]
https://github.com/GeraAlcantara/cards-memory-game/pull/16 [from ABHIGYAN-MOHANTA:main](https://github.com/GeraAlcantara/cards-memory-game/commit/c04b3261cc543195062e52fb81e690733c182614)

**Comment by ABHIGYAN-MOHANTA** [comment]
Thanks man.
