### ISSUE TITLE
Medium Post 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#62]
# Low or NON-CODE Contributions 

If you are looking for a non-code contribution I'll appreciated a Blog post on Medium. 

In order to track your contribution of the post on medium please follow the guide lines in [CONTRIBUTING](https://github.com/GeraAlcantara/cards-memory-game/blob/main/CONTRIBUTING.md) 

And follow the examples on [Non-code track examples](https://github.com/GeraAlcantara/cards-memory-game/blob/main/NON_CODE_CONTRIBUTIONS/EXAMPLES.md)

**Comment by Siddharth9890** [comment]
I can do this can you describe a little bit more what we need to exactly

**Comment by GeraAlcantara** [comment]
Hi @Siddharth9890 
A blog post inviting to the people to contribute to low-non-code issues during the Hacktoberfest it no have to be related to this repo precisely just to participate on the event in general
