### ISSUE TITLE
Adding a restart/continue playing button

### ISSUE THREAD

**Issue by rahmlad-aramide** [GeraAlcantara/cards-memory-game#63]
After completing the game for the first time, that's where it ends, it's not bad if there's a button to continue playing the game instead of refreshing the website, by so doing there can be a score component as well which will track the player's score i.e number of time they've played

**Comment by GeraAlcantara** [comment]
No intended for this version since is no a proper UI / UX prepare for that, esthetics is importan  as it is the UX
