### ISSUE TITLE
Missing quotation mark in gameBase/index.html

### ISSUE THREAD

**Issue by arthurmatthew** [GeraAlcantara/cards-memory-game#7]
It looks like the `div` opening tags on line 47 and 51 are missing a quotation mark in the data-framework attribute.

Example:
`<div class="memory-card" data-framework=vue">`
Should be:
`<div class="memory-card" data-framework="vue">`

**Comment by arthurmatthew** [comment]
If you'd like to assign me I am able to fix this.

**Comment by GeraAlcantara** [comment]
please do
