### ISSUE TITLE
Add Translation README.MD for Spanish 

### ISSUE THREAD

**Issue by GeraAlcantara** [GeraAlcantara/cards-memory-game#9]
Translate the README File to Spanish 

Instead of modifying the README.md can you please ad a README[ES_MX].md version

**Comment by 1-Sanchit-1** [comment]
hello sir, 
I am interested in translate README File into Spanish . 
Can u assign this issue to me .

**Comment by GeraAlcantara** [comment]
Sure @1-Sanchit-1 

just pleas Instead of modifying the README.md can you please ad a README[ES_MX].md version on.

I have made a new commit to have a Base 


translation/README[ES_MX].md
